apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaithAppsrv
    service: chaithAppsrv
  name: chaithAppsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: chaithApp