name: Upload to s3

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # specify your desired Go version

      - name: Build Go Project
        run: | 
            go mod init chaithApp
            go mod tidy
            export GOARCH=amd64
            export CGO_ENABLED=0
            go build -o main main.go

      - name: Zip the Binary and Associated Files
        run: |
          zip -r main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # replace with your desired region

      - name: Upload to S3
        run: |
          aws s3 cp ./main.zip s3://githubworkflowtest1/test1/main.zip --region us-east-1
